version: '3'
services:
  api:
    build: .
    container_name: flavor-api
    environment:
      - FLAVOR_API_JWT_SECRET=changeme
    ports:
      - 3000:3000
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=flavors
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=flavors
    ports:
      - 5432:5432
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
