version: '3'
services:
  api:
    build: .
    image: gusta-api:latest
    container_name: gusta-api
    ports:
      - ${API_PORT:-3000}:3000
    environment:
      API_TOKEN_SECRET: changeme
      DB_HOST: database
      DB_PASS: changeme
      VIRTUAL_HOST: ${API_HOST}
      LETSENCRYPT_HOST: ${API_HOST}
    depends_on:
      - database
  database:
    image: postgres:latest
    container_name: gusta-api-pg
    environment:
      - POSTGRES_USER=flavors
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=flavors
  proxy:
    image: nginx
    container_name: gusta-api-proxy
    restart: always
    depends_on:
      - api
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
  reloader:
    image: jwilder/docker-gen
    command: -notify-sighup gusta-api-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: gusta-api-reloader
    restart: always
    depends_on:
      - proxy
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: gusta-api-letsencrypt
    restart: always
    depends_on:
      - reloader
    environment:
      NGINX_PROXY_CONTAINER: gusta-api-proxy
      NGINX_DOCKER_GEN_CONTAINER: gusta-api-reloader
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
volumes:
  conf:
  vhost:
  html:
  certs:
