version: 2.1

orbs:
  mattermost-notify: bulletlogic/mattermost-notify@0.0.4

jobs:
  build:
    machine: true
    working_directory: ~/gusta-api
    steps:
      - checkout
      - run:
          name: Set environment variables
          command: |
            echo 'export CODECOV_TOKEN="$CODECOV_TOKEN_API"' >> $BASH_ENV
            source $BASH_ENV
      - run: docker-compose up -d
      - run: docker-compose exec api npm run migrate
      - run: docker-compose exec api npm test
      - run: docker-compose exec api bash "CODECOV_TOKEN=$CODECOV_TOKEN_API npx codecov"
  notify_success:
    docker:
      - image: byrnedo/alpine-curl:latest
    steps:
      - mattermost-notify/notify_on_success:
          webhook: '$MATTERMOST_WEBHOOK_API'
  notify_failure:
    docker:
      - image: byrnedo/alpine-curl:latest
    steps:
      - mattermost-notify/notify_on_failure:
          webhook: '$MATTERMOST_WEBHOOK_API'

workflows:
  version: 2
  main_workflow:
    jobs:
      - build:
          context: builds
      - notify_success:
          context: webhooks
          requires:
            - build
      - notify_failure:
          context: webhooks
          requires:
            - build
